### ISSUE TITLE
account example error on node 0.8.4

### ISSUE THREAD

**Issue by ghost** [kilianc/node-apiserver#19]
Trace below. This happens because the domain option is copied to the ApiServer instance. In 0.8.x EventEmitter tries to 'enter' the domain. I changed the name of the domain option to 'domain_compat' and to get it working. 

The real fix? Use a sub-object for the EventEmitter instead of inheriting it? Namespace the options? Both inconvenient.

events.js:80
      this.domain.enter();
                  ^
TypeError: Object localhost has no method 'enter'
    at EventEmitter.emit (events.js:80:19)
    at onRequest (.... /node-apiserver/examples/account/node_modules/apiserver/lib/apiserver.js:120:8)
    at Server.EventEmitter.emit (events.js:91:17)
    at HTTPParser.parser.onIncoming (http.js:1783:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete](http.js:111:23)
    at Socket.socket.ondata (http.js:1680:22)
    at TCP.onread (net.js:410:27)

**Comment by kilianc** [comment]
Renaming could be a way, looking into this.
