### ISSUE TITLE
ReferenceError: __stack is not defined

### ISSUE THREAD

**Issue by jessecravens** [kilianc/node-apiserver#22]
on node v0.8.14, receive this error when running the account example. 

console-trace/console-trace.js:43
      arguments[0] = console.traceFormat(__stack[1], name) + pad + arguments[0]

ReferenceError: __stack is not defined
    at Object.forEach.console.(anonymous function) [as info](/Users/username/Code/node_projects/node-apiserver/examples/account/node_modules/console-trace/console-trace.js:43:42)
    at Server.mongodbDb.open.ApiServer.timeout (/Users/username/Code/node_projects/node-apiserver/examples/account/server.js:25:13)
    at Server.g (events.js:192:14)
    at Server.EventEmitter.emit (events.js:93:17)
    at Server._listen2 (net.js:922:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by neverfox** [comment]
Same on v0.8.20, both examples. On v0.10.5, I get:

node-apiserver\examples\account\node_modules\console-trace\console-trace.js:43
      arguments[0] = console.traceFormat(__stack[1], name) + pad + arguments[0
                                         ^
ReferenceError: __stack is not defined
    at Console.console.(anonymous function) [as info](node-apiserverexamplesaccountnode_modulesconsole-traceconsole-trace.js:43:42)
    at Server.<anonymous> (node-apiserver\examples\account\server.js:25:13)
    at Server.g (events.js:175:14)
    at Server.EventEmitter.emit (events.js:92:17)
    at net.js:1035:10
    at process._tickCallback (node.js:415:13)

But by the looks of it, the repo might be dead. I hope not. Looks cool.
